import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { TalkBlockHeader } from "@/components/TalkBlockChrome";
import { useSettings } from "@/store/SettingsContext";
import { colors, spacing } from "@/theme";

export default function SituationsScreen() {
  const { settings, updateSettings } = useSettings();
  const toggle = (id: string) => void updateSettings({ situations: settings.situations.map((item) => item.id === id ? { ...item, enabled: !item.enabled } : item) });
  return <SafeAreaView style={styles.safe}><TalkBlockHeader title="Situations" /><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>RECOGNIZE THE SCENE</Text><Text style={styles.title}>TalkBlock listens for the scene you choose.</Text><Text style={styles.intro}>Pick the situations to watch for when you start listening.</Text>{settings.situations.map((item) => <Pressable key={item.id} onPress={() => toggle(item.id)} style={[styles.card, item.enabled && styles.selected]}><Text style={styles.icon}>{item.id === "tornado" ? "≋" : item.id === "student" ? "◇" : item.id === "boss" ? "▣" : "♙"}</Text><View style={styles.copy}><Text style={styles.name}>{item.title}</Text><Text style={styles.detail}>{item.description}</Text></View><View style={[styles.check, item.enabled && styles.checkSelected]}><Text style={styles.checkText}>{item.enabled ? "✓" : ""}</Text></View></Pressable>)}<Pressable onPress={() => router.back()} style={styles.continue}><Text style={styles.continueText}>Continue</Text></Pressable></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { backgroundColor: colors.background, flex: 1 }, content: { padding: spacing.md }, eyebrow: { color: colors.primary, fontSize: 10, fontWeight: "800", letterSpacing: 1.4 }, title: { color: colors.text, fontSize: 17, fontWeight: "600", lineHeight: 22, marginTop: spacing.xs }, intro: { color: colors.textMuted, fontSize: 13, lineHeight: 19, marginBottom: spacing.md, marginTop: spacing.xs }, card: { alignItems: "center", borderColor: colors.border, borderRadius: 12, borderWidth: 1, flexDirection: "row", marginBottom: spacing.sm, minHeight: 68, padding: spacing.md }, selected: { backgroundColor: "#FFF0F1", borderColor: "#F0AEB3" }, icon: { color: colors.primary, fontSize: 22, width: 32 }, copy: { flex: 1 }, name: { color: colors.text, fontSize: 14, fontWeight: "700" }, detail: { color: colors.textMuted, fontSize: 12, lineHeight: 16, marginTop: 2 }, check: { alignItems: "center", borderColor: "#D4D4D4", borderRadius: 12, borderWidth: 1, height: 20, justifyContent: "center", width: 20 }, checkSelected: { backgroundColor: colors.primary, borderColor: colors.primary }, checkText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" }, continue: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 10, marginTop: spacing.md, minHeight: 42, justifyContent: "center" }, continueText: { color: "#FFFFFF", fontSize: 14, fontWeight: "700" } });
